using System.Linq;
using Kubuno.Views.Designer;
using Kubuno.Views.Designer.PropertyBrowser;
using Kubuno.Views.Designer.Registry;
using Kubuno.Views.Designer.Toolbox;
using Microsoft.VisualStudio.TestTools.UnitTesting;

namespace Kubuno.Views.Tests.Designer.Toolbox
{
    /// <summary>
    /// docs/STORAGE-COMPONENTS.md: the storage components in the designer - their Toolbox tab ("Storage" /
    /// "Stockage"), the component tray, the Properties window (the back-end and hive drop-downs, the localized
    /// category) and the default events. The fixture is the real <c>kubuno/registry</c> answer of
    /// <c>kubuno-views-ls</c> for the storage sample (its scan of <c>kubuno-app-storage-components</c>, reached through
    /// the <c>kubuno</c> crate's workspace dependencies), regenerated by the language server's ignored test
    /// <c>storage_registry_fixture</c>.
    /// </summary>
    [TestClass]
    public class StorageToolboxTests
    {
        private static ComponentRegistry Registry() => ComponentRegistry.FromJson(TestFixtures.ReadAllText("storage.registry.json"));

        [TestCleanup]
        public void ResetLanguage() => DesignerText.ForceFrench = null;

        [TestMethod]
        public void The_storage_components_have_their_own_toolbox_tab()
        {
            DesignerText.ForceFrench = false;
            var layout = NativeToolboxInstaller.Layout(Registry()).ToList();
            CollectionAssert.AreEqual(
                new[] { "FileStore", "KeyValueStore", "RegistryKey", "SecretStore", "Settings" },
                layout.Where(i => i.Tab == "Storage").Select(i => i.Component).ToArray(),
                "alphabetical, like the WinForms Toolbox");
            DesignerText.ForceFrench = true;
            Assert.IsTrue(NativeToolboxInstaller.Layout(Registry()).All(i => i.Tab == "Stockage"));
            Assert.AreEqual("Stockage", PropertyCategoryMap.DisplayName("Storage"), "the properties' category, localized");
            CollectionAssert.Contains(DesignerText.AllToolboxTabNames(), "Stockage", "a stale tab of an earlier session is cleaned up");
        }

        [TestMethod]
        public void The_components_go_to_the_tray_with_their_default_events_and_drop_downs()
        {
            var registry = Registry();
            var settings = registry.Find("Settings")!;
            Assert.IsTrue(settings.NonVisual);
            Assert.AreEqual("kubuno_app_storage_components", settings.CrateName);
            Assert.AreEqual("OnSettingChanged", settings.DefaultEventFor(false)?.Name, "a double-click creates the SettingChanged handler");
            Assert.AreEqual("SettingChangedEventArgs", settings.FindEvent("OnSettingChanged")!.ArgsType);
            Assert.AreEqual("Schema", settings.DefaultProperty);
            var backend = settings.Properties.Single(p => p.Name == "Backend");
            CollectionAssert.AreEqual(new[] { "Auto", "File", "Registry", "Memory" }, backend.Kind.EnumVariants.ToArray());
            Assert.AreEqual("Auto", backend.Default);
            Assert.AreEqual("Storage", backend.Category);

            var key = registry.Find("RegistryKey")!;
            Assert.IsTrue(key.NonVisual);
            Assert.AreEqual("OnValueChanged", key.DefaultEventFor(false)?.Name);
            CollectionAssert.AreEqual(new[] { "CurrentUser", "LocalMachine", "ClassesRoot", "Users", "CurrentConfig" }, key.Properties.Single(p => p.Name == "Hive").Kind.EnumVariants.ToArray());
            CollectionAssert.AreEqual(new[] { "Default", "Registry32", "Registry64" }, key.Properties.Single(p => p.Name == "View").Kind.EnumVariants.ToArray());
            Assert.AreEqual("false", key.Properties.Single(p => p.Name == "Writable").Default, "read-only unless asked");

            var secrets = registry.Find("SecretStore")!;
            Assert.IsTrue(secrets.NonVisual);
            CollectionAssert.AreEqual(new[] { "Os", "Memory" }, secrets.Properties.Single(p => p.Name == "Backend").Kind.EnumVariants.ToArray());

            // Lot ST-2: the key-value store and the file store.
            var kv = registry.Find("KeyValueStore")!;
            Assert.IsTrue(kv.NonVisual);
            Assert.AreEqual("kubuno_app_storage_components", kv.CrateName);
            var files = registry.Find("FileStore")!;
            Assert.IsTrue(files.NonVisual);
            CollectionAssert.AreEqual(new[] { "Data", "Cache", "Temp" }, files.Properties.Single(p => p.Name == "Kind").Kind.EnumVariants.ToArray());
            Assert.AreEqual("registry-key", key.Properties.Single(p => p.Name == "Path").Editor, "the Registry key picker");
        }
    }
}
