using System;
using System.IO;
using System.Text;

namespace Kubuno.Rust.Logic.ProjectGeneration
{
    /// <summary>
    /// Builds the text of one generated <c>.rsproj</c> (docs/RSPROJ.md work package 5). Mirrors
    /// <c>samples/hello-rust/hello-rust.rsproj</c>'s own hand-written shape: the SDK import line,
    /// then a single <c>PropertyGroup</c> with only the properties that differ from
    /// <c>Kubuno.Rust.Sdk/Sdk.props</c>'s defaults - a generated project should read exactly like
    /// one a developer would have hand-written for the same package.
    /// </summary>
    public static class RsprojTemplate
    {
        /// <param name="packageName">The Cargo package name - written as <c>&lt;CargoPackage&gt;</c>.</param>
        /// <param name="sdkVersion">Pinned <c>Kubuno.Rust.Sdk</c> version (<see cref="RsprojGenerationOptions.SdkVersion"/>).</param>
        /// <param name="cargoBin">
        /// The <c>[[bin]]</c> target to build/run, written as <c>&lt;CargoBin&gt;</c> only when
        /// given (a package with more than one bin target - see
        /// <see cref="RsprojGenerationPlanner"/>'s own remarks for when this is set); <see
        /// langword="null"/>/empty for a single-bin (or library-only) package, where cargo's own
        /// default resolution is unambiguous and nothing needs to be written.
        /// </param>
        /// <param name="manifestPathRelativeToProject">
        /// Relative (or absolute) path from the generated project's own directory to its
        /// <c>Cargo.toml</c>, written as <c>&lt;CargoManifestPath&gt;</c> only when it is anything
        /// other than the sibling default ("Cargo.toml") - see
        /// <see cref="RsprojGenerationOptions.ResolveProjectDirectory"/>.
        /// </param>
        /// <param name="workspaceBuild">
        /// Writes <c>&lt;CargoBuildScope&gt;Workspace&lt;/CargoBuildScope&gt;</c>: the project builds the whole Cargo
        /// workspace (once per build for all its projects) instead of its own package - see
        /// <see cref="RsprojGenerationPlanner"/> for when the planner asks for it.
        /// </param>
        public static string Build(
            string packageName,
            string sdkVersion,
            string? cargoBin,
            string? manifestPathRelativeToProject,
            bool workspaceBuild = false)
        {
            if (string.IsNullOrWhiteSpace(packageName))
            {
                throw new ArgumentException("Package name must not be empty.", nameof(packageName));
            }

            if (string.IsNullOrWhiteSpace(sdkVersion))
            {
                throw new ArgumentException("SDK version must not be empty.", nameof(sdkVersion));
            }

            var builder = new StringBuilder();
            builder.Append("<Project Sdk=\"Kubuno.Rust.Sdk/").Append(sdkVersion).Append("\">").Append('\n');
            builder.Append('\n');
            builder.Append("  <!-- Generated by \"Kubuno: Generate Visual Studio Projects\" (docs/RSPROJ.md work package 5). This file is").Append('\n');
            builder.Append("       yours: it is never overwritten by a later run - edit it freely, or delete it and re-run the command").Append('\n');
            builder.Append("       to get a fresh default. -->").Append('\n');
            builder.Append("  <PropertyGroup>").Append('\n');
            builder.Append("    <CargoPackage>").Append(EscapeXmlText(packageName)).Append("</CargoPackage>").Append('\n');

            if (!string.IsNullOrEmpty(cargoBin))
            {
                builder.Append("    <CargoBin>").Append(EscapeXmlText(cargoBin!)).Append("</CargoBin>").Append('\n');
            }

            if (!string.IsNullOrEmpty(manifestPathRelativeToProject) &&
                !string.Equals(manifestPathRelativeToProject, "Cargo.toml", StringComparison.OrdinalIgnoreCase))
            {
                var normalized = manifestPathRelativeToProject!.Replace('/', Path.DirectorySeparatorChar);
                builder.Append("    <CargoManifestPath>").Append(EscapeXmlText(normalized)).Append("</CargoManifestPath>").Append('\n');
            }

            if (workspaceBuild)
            {
                builder.Append("    <!-- The workspace's programs share most of their crates: build the whole workspace in one cargo run, so that").Append('\n');
                builder.Append("         a solution build compiles each shared crate once, with one feature set (docs/RSPROJ.md, \"Cargo workspaces\"). -->").Append('\n');
                builder.Append("    <CargoBuildScope>Workspace</CargoBuildScope>").Append('\n');
            }

            builder.Append("  </PropertyGroup>").Append('\n');
            builder.Append('\n');
            builder.Append("</Project>").Append('\n');
            return builder.ToString();
        }

        private static string EscapeXmlText(string value) => System.Security.SecurityElement.Escape(value) ?? value;
    }
}
