// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer (Visual Studio) from
//     source.extension.vsixmanifest. Regenerate it from the manifest designer if the
//     manifest's Identity/Metadata section changes; MSBuild CLI builds do not do this
//     automatically, so it is checked into source control.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Kubuno.VisualStudio
{
    internal sealed partial class Vsix
    {
        public const string Id = "Kubuno.VisualStudio.a3f0e6c2-5b1d-4e6a-8b1a-9c1a2f3e4d5c";
        public const string Name = "Kubuno for Visual Studio";
        public const string Description = @"Rust language support (rust-analyzer, syntax coloring, rustfmt) for developing Kubuno modules in Visual Studio.";
        public const string Language = "en-US";
        public const string Version = "1.0.0";
        public const string Author = "Kubuno";
        public const string Tags = "Rust;Cargo;rust-analyzer;Kubuno";
    }
}
