// <auto-generated>
// Generated by tools/generate-control-icons.ps1 - do not edit by hand (rerun the script instead).
// </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace Kubuno.VisualStudio.Core.SolutionExplorer
{
    /// <summary>
    /// The Kubuno control icons of <c>KubunoControls.imagemanifest</c> (docs/DESIGNER.md section 11): one
    /// Lucide-based icon per kubuno-views component, used by the .kbview designer's Toolbox AND the
    /// .kbview element nodes of Solution Explorer. Rust code symbols keep Visual Studio's own
    /// <c>KnownMonikers</c> (<see cref="SymbolMonikerNames"/>) so they look like the rest of the IDE.
    /// </summary>
    public static class ControlIcons
    {
        /// <summary>The manifest's <c>ControlImagesGuid</c>.</summary>
        public static readonly Guid ImagesGuid = new Guid("3b6e1f24-9c7a-4d5e-8f21-6a0c4b9d2e71");

        /// <summary>The generic control icon, for an element the table does not know.</summary>
        public const int FallbackId = 1;

        private static readonly Dictionary<string, int> Ids = new Dictionary<string, int>(StringComparer.Ordinal)
        {
            ["Button"] = 2, // Lucide "square-mouse-pointer"
            ["Card"] = 3, // Lucide "panel-top"
            ["Stack"] = 4, // Lucide "rows-3"
            ["Switch"] = 5, // Lucide "toggle-right"
            ["TextField"] = 6, // Lucide "text-cursor-input"
            ["Badge"] = 7, // Lucide "badge"
            ["Callout"] = 8, // Lucide "info"
            ["EmptyState"] = 9, // Lucide "inbox"
            ["Icon"] = 10, // Lucide "image"
            ["Label"] = 11, // Lucide "type"
            ["LinkLabel"] = 12, // Lucide "link"
            ["ProgressBar"] = 13, // custom (Lucide style)
            ["Separator"] = 14, // Lucide "separator-horizontal"
            ["Spinner"] = 15, // Lucide "loader"
            ["ColorField"] = 16, // Lucide "palette"
            ["ComboBox"] = 17, // Lucide "text-select"
            ["DatePicker"] = 18, // Lucide "calendar"
            ["Dropdown"] = 19, // Lucide "square-chevron-down"
            ["MaskedField"] = 20, // Lucide "rectangle-ellipsis"
            ["Option"] = 21, // Lucide "check"
            ["SearchField"] = 22, // Lucide "search"
            ["TextArea"] = 23, // Lucide "text"
            ["Accordion"] = 24, // Lucide "list-collapse"
            ["AccordionSection"] = 25, // Lucide "chevrons-down-up"
            ["Breadcrumb"] = 26, // Lucide "chevrons-right"
            ["BreadcrumbItem"] = 27, // Lucide "chevron-right"
            ["GroupBox"] = 28, // Lucide "group"
            ["Panel"] = 29, // Lucide "square-dashed"
            ["ScrollArea"] = 30, // Lucide "scroll-text"
            ["Splitter"] = 31, // Lucide "columns-2"
            ["Step"] = 32, // Lucide "circle-check"
            ["Stepper"] = 33, // Lucide "list-ordered"
            ["TabItem"] = 34, // Lucide "app-window"
            ["Tabs"] = 35, // Lucide "panels-top-left"
            ["Toolbar"] = 36, // Lucide "panel-top-dashed"
            ["ToolbarItem"] = 37, // Lucide "mouse-pointer-2"
            ["CheckedListBox"] = 38, // Lucide "list-checks"
            ["Column"] = 39, // Lucide "columns-3"
            ["DataTable"] = 40, // Lucide "table"
            ["Item"] = 41, // Lucide "list-start"
            ["ListBox"] = 42, // Lucide "list"
            ["ListView"] = 43, // Lucide "layout-list"
            ["MonthCalendar"] = 44, // Lucide "calendar-days"
            ["TreeView"] = 45, // Lucide "folder-tree"
            ["CheckBox"] = 46, // Lucide "square-check"
            ["IconButton"] = 47, // Lucide "circle-plus"
            ["NumericField"] = 48, // Lucide "chevrons-up-down"
            ["RadioButton"] = 49, // Lucide "circle-dot"
            ["Slider"] = 50, // Lucide "sliders-horizontal"
        };

        /// <summary>The image id for element <paramref name="tag"/> (<see cref="FallbackId"/> when unknown).</summary>
        public static int IdFor(string? tag) => tag != null && Ids.TryGetValue(tag, out var id) ? id : FallbackId;

        /// <summary>Every component that has its own icon.</summary>
        public static IEnumerable<string> KnownComponents => Ids.Keys;
    }
}