using System.Collections.Generic;

namespace Kubuno.Rust.Logic.ProjectProperties
{
    /// <summary>
    /// The category slugs crates.io accepts in Cargo.toml's <c>categories</c> (https://crates.io/category_slugs),
    /// offered by the Package page's "Categories" checklist (docs/RSPROJ.md, "Project properties like .NET").
    /// crates.io rejects a publish with an unknown slug, hence a fixed list instead of free text; it changes
    /// rarely (last reviewed 2026-09).
    /// </summary>
    public static class CratesIoCategories
    {
        public static IReadOnlyList<string> All { get; } = new[]
        {
            "accessibility",
            "aerospace",
            "aerospace::drones",
            "aerospace::protocols",
            "aerospace::simulation",
            "aerospace::space-protocols",
            "aerospace::unmanned-aerial-vehicles",
            "algorithms",
            "api-bindings",
            "asynchronous",
            "authentication",
            "caching",
            "command-line-interface",
            "command-line-utilities",
            "compilers",
            "compression",
            "computer-vision",
            "concurrency",
            "config",
            "cryptography",
            "cryptography::cryptocurrencies",
            "data-structures",
            "database",
            "database-implementations",
            "date-and-time",
            "development-tools",
            "development-tools::build-utils",
            "development-tools::cargo-plugins",
            "development-tools::debugging",
            "development-tools::ffi",
            "development-tools::procedural-macro-helpers",
            "development-tools::profiling",
            "development-tools::testing",
            "email",
            "embedded",
            "emulators",
            "encoding",
            "external-ffi-bindings",
            "filesystem",
            "finance",
            "game-development",
            "game-engines",
            "games",
            "graphics",
            "gui",
            "hardware-support",
            "internationalization",
            "localization",
            "mathematics",
            "memory-management",
            "multimedia",
            "multimedia::audio",
            "multimedia::encoding",
            "multimedia::images",
            "multimedia::video",
            "network-programming",
            "no-std",
            "no-std::no-alloc",
            "os",
            "os::android-apis",
            "os::freebsd-apis",
            "os::linux-apis",
            "os::macos-apis",
            "os::unix-apis",
            "os::windows-apis",
            "parser-implementations",
            "parsing",
            "rendering",
            "rendering::data-formats",
            "rendering::engine",
            "rendering::graphics-api",
            "rust-patterns",
            "science",
            "science::bioinformatics",
            "science::geo",
            "science::neuroscience",
            "science::robotics",
            "simulation",
            "template-engine",
            "text-editors",
            "text-processing",
            "value-formatting",
            "virtualization",
            "visualization",
            "wasm",
            "web-programming",
            "web-programming::http-client",
            "web-programming::http-server",
            "web-programming::websocket",
        };
    }
}
